openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /magic:
    post:
      tags:
        - answercontroller
      operationId: magic8Ball
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Answer'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Answer'
  /word:
    get:
      tags:
        - word-controller
      operationId: getRandomWord
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /quote:
    get:
      tags:
        - quotecontroller
      operationId: quoteAPI
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Quote'
components:
  schemas:
    Answer:
      type: object
      properties:
        id:
          type: integer
          format: int32
        question:
          type: string
        answer:
          type: string
    Quote:
      type: object
      properties:
        author:
          type: string
        id:
          type: integer
          format: int32
        quote:
          type: string
